version: '3.4'

services:
  translator:
    environment:
      - YANDEX_API_TOKEN=t1.9euelZrIiZGbz5aMx8zJzpLOx4nIlO3rnpWazY6LjJuXicqUmoqYyc-Tkpnl8_dwfwhf-e8WPV98_t3z9zAuBl_57xY9X3z-.Qlf1JukfWUirbsfafWzZlJ5StRPUuCd7NtroKHgC_fWESruOEf8dFB_CCVUJZr7tEMw7ierc5yGsN4Ytl52KDQ
      - YANDEX_FOLDER_ID=b1gpmmgv8etd5678mt5q
      - H2_DB_NAME=my_db
      - H2_USERNAME=kuk
      - H2_PASSWORD=k
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081/tcp"